# Generated by Django 5.2.5 on 2025-09-14 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('description', models.CharField(max_length=50, verbose_name='Возрастная группа')),
            ],
            options={
                'verbose_name': 'Возрастная группа',
                'verbose_name_plural': 'Возрастные группы',
            },
        ),
        migrations.CreateModel(
            name='CallFrequency',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('description', models.CharField(max_length=50, verbose_name='Периодичность обращений')),
            ],
            options={
                'verbose_name': 'Периодичность обращения',
                'verbose_name_plural': 'Периодичности обращений',
            },
        ),
        migrations.CreateModel(
            name='CrisisSituation',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('description', models.CharField(max_length=50, verbose_name='Периодичность обращений')),
            ],
            options={
                'verbose_name': 'Кризисность ситуации',
                'verbose_name_plural': 'Кризисность ситуации',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DurationCategory',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('description', models.CharField(max_length=50, verbose_name='Продолжительность контакта')),
            ],
            options={
                'verbose_name': 'Категория продолжительности',
                'verbose_name_plural': 'Категории продолжительности',
            },
        ),
        migrations.CreateModel(
            name='EmotionalState',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('description', models.CharField(max_length=100, verbose_name='Эмоциональное состояние')),
            ],
            options={
                'verbose_name': 'Эмоциональное состояние',
                'verbose_name_plural': 'Эмоциональные состояния',
            },
        ),
        migrations.CreateModel(
            name='EmotionDynamic',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('description', models.CharField(max_length=100, verbose_name='Динамика переживаний')),
            ],
            options={
                'verbose_name': 'Динамика переживаний',
                'verbose_name_plural': 'Динамики переживаний',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('description', models.CharField(max_length=20, verbose_name='Пол абонента')),
            ],
            options={
                'verbose_name': 'Пол абонента',
                'verbose_name_plural': 'Пол абонента',
            },
        ),
        migrations.CreateModel(
            name='HelpProvided',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('description', models.CharField(max_length=200, verbose_name='Предоставленная помощь')),
            ],
            options={
                'verbose_name': 'Предоставленная помощь',
                'verbose_name_plural': 'Предоставленные виды помощи',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('description', models.CharField(max_length=50, verbose_name='Семейное положение')),
            ],
            options={
                'verbose_name': 'Семейное положение',
                'verbose_name_plural': 'Семейное положение',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Код проблемы')),
                ('group', models.PositiveIntegerField(verbose_name='Группа')),
                ('description', models.CharField(max_length=200, verbose_name='Тип обращения')),
            ],
            options={
                'verbose_name': 'Проблема',
                'verbose_name_plural': 'Проблемы',
            },
        ),
        migrations.CreateModel(
            name='ProblemDuration',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('description', models.CharField(max_length=50, verbose_name='Длительность существования проблемы')),
            ],
            options={
                'verbose_name': 'Длительность проблемы',
                'verbose_name_plural': 'Длительности проблем',
            },
        ),
        migrations.CreateModel(
            name='SocialStatus',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('description', models.CharField(max_length=100, verbose_name='Социальное положение')),
            ],
            options={
                'verbose_name': 'Социальное положение',
                'verbose_name_plural': 'Социальное положение',
            },
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateField(verbose_name='Дата обращения')),
                ('call_time', models.TimeField(verbose_name='Время обращения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tdapp.agegroup', verbose_name='Возрастная группа')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Консультант')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tdapp.callfrequency', verbose_name='Периодичность обращений')),
                ('crisis_situation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tdapp.crisissituation', verbose_name='Кризисность ситуации')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tdapp.durationcategory', verbose_name='Продолжительность контакта')),
                ('emotional_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tdapp.emotionalstate', verbose_name='Эмоциональное состояние')),
                ('emotion_dynamic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tdapp.emotiondynamic', verbose_name='Динамика переживаний')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tdapp.gender', verbose_name='Пол абонента')),
                ('help_provided', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tdapp.helpprovided', verbose_name='Предоставленная помощь')),
                ('marital_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tdapp.maritalstatus', verbose_name='Семейное положение')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tdapp.problem', verbose_name='Проблема')),
                ('problem_duration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tdapp.problemduration', verbose_name='Длительность существования проблемы')),
                ('social_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tdapp.socialstatus', verbose_name='Социальное положение')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
                'ordering': ['-call_date', '-call_time'],
            },
        ),
    ]
